# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/pwm_model/pwm_model.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pwm_model || ORIG_REF_NAME==pwm_model} -quiet] -quiet

# IP: bd/pwm_model/ip/pwm_model_counter_10_0_0/pwm_model_counter_10_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pwm_model_counter_10_0_0 || ORIG_REF_NAME==pwm_model_counter_10_0_0} -quiet] -quiet

# IP: bd/pwm_model/ip/pwm_model_comparator_10_0_0/pwm_model_comparator_10_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pwm_model_comparator_10_0_0 || ORIG_REF_NAME==pwm_model_comparator_10_0_0} -quiet] -quiet

# IP: bd/pwm_model/ip/pwm_model_xlconstant_0_0/pwm_model_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pwm_model_xlconstant_0_0 || ORIG_REF_NAME==pwm_model_xlconstant_0_0} -quiet] -quiet

# XDC: bd/pwm_model/pwm_model_ooc.xdc
