# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/three_ADC_constraints.xdc

# Block Designs: bd/adc_design/adc_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adc_design || ORIG_REF_NAME==adc_design} -quiet] -quiet

# IP: bd/adc_design/ip/adc_design_processing_system7_0_0/adc_design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adc_design_processing_system7_0_0 || ORIG_REF_NAME==adc_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/adc_design/ip/adc_design_xadc_wiz_0_0/adc_design_xadc_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adc_design_xadc_wiz_0_0 || ORIG_REF_NAME==adc_design_xadc_wiz_0_0} -quiet] -quiet

# IP: bd/adc_design/ip/adc_design_ps7_0_axi_periph_0/adc_design_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adc_design_ps7_0_axi_periph_0 || ORIG_REF_NAME==adc_design_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/adc_design/ip/adc_design_rst_ps7_0_100M_0/adc_design_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adc_design_rst_ps7_0_100M_0 || ORIG_REF_NAME==adc_design_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/adc_design/ip/adc_design_auto_pc_0/adc_design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adc_design_auto_pc_0 || ORIG_REF_NAME==adc_design_auto_pc_0} -quiet] -quiet

# XDC: bd/adc_design/adc_design_ooc.xdc
