# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Avnet/project_PL_PS_new/project_PL_PS_new.srcs/sources_1/bd/design_ps_pl/ip/design_ps_pl_axi_smc_0/design_ps_pl_axi_smc_0.xci
# IP: The module: 'design_ps_pl_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Avnet/project_PL_PS_new/project_PL_PS_new.srcs/sources_1/bd/design_ps_pl/ip/design_ps_pl_axi_smc_0/bd_0/bd_de28.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Avnet/project_PL_PS_new/project_PL_PS_new.srcs/sources_1/bd/design_ps_pl/ip/design_ps_pl_axi_smc_0/bd_0/ip/ip_0/bd_de28_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Avnet/project_PL_PS_new/project_PL_PS_new.srcs/sources_1/bd/design_ps_pl/ip/design_ps_pl_axi_smc_0/bd_0/ip/ip_1/bd_de28_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Avnet/project_PL_PS_new/project_PL_PS_new.srcs/sources_1/bd/design_ps_pl/ip/design_ps_pl_axi_smc_0/bd_0/ip/ip_2/bd_de28_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Avnet/project_PL_PS_new/project_PL_PS_new.srcs/sources_1/bd/design_ps_pl/ip/design_ps_pl_axi_smc_0/bd_0/ip/ip_3/bd_de28_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Avnet/project_PL_PS_new/project_PL_PS_new.srcs/sources_1/bd/design_ps_pl/ip/design_ps_pl_axi_smc_0/bd_0/ip/ip_4/bd_de28_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Avnet/project_PL_PS_new/project_PL_PS_new.srcs/sources_1/bd/design_ps_pl/ip/design_ps_pl_axi_smc_0/bd_0/ip/ip_5/bd_de28_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Avnet/project_PL_PS_new/project_PL_PS_new.srcs/sources_1/bd/design_ps_pl/ip/design_ps_pl_axi_smc_0/bd_0/ip/ip_6/bd_de28_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Avnet/project_PL_PS_new/project_PL_PS_new.srcs/sources_1/bd/design_ps_pl/ip/design_ps_pl_axi_smc_0/bd_0/ip/ip_7/bd_de28_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Avnet/project_PL_PS_new/project_PL_PS_new.srcs/sources_1/bd/design_ps_pl/ip/design_ps_pl_axi_smc_0/bd_0/ip/ip_8/bd_de28_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Avnet/project_PL_PS_new/project_PL_PS_new.srcs/sources_1/bd/design_ps_pl/ip/design_ps_pl_axi_smc_0/bd_0/ip/ip_9/bd_de28_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Avnet/project_PL_PS_new/project_PL_PS_new.srcs/sources_1/bd/design_ps_pl/ip/design_ps_pl_axi_smc_0/bd_0/ip/ip_10/bd_de28_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Avnet/project_PL_PS_new/project_PL_PS_new.srcs/sources_1/bd/design_ps_pl/ip/design_ps_pl_axi_smc_0/bd_0/ip/ip_11/bd_de28_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Avnet/project_PL_PS_new/project_PL_PS_new.srcs/sources_1/bd/design_ps_pl/ip/design_ps_pl_axi_smc_0/bd_0/ip/ip_12/bd_de28_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Avnet/project_PL_PS_new/project_PL_PS_new.srcs/sources_1/bd/design_ps_pl/ip/design_ps_pl_axi_smc_0/bd_0/ip/ip_1/bd_de28_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Avnet/project_PL_PS_new/project_PL_PS_new.srcs/sources_1/bd/design_ps_pl/ip/design_ps_pl_axi_smc_0/bd_0/ip/ip_1/bd_de28_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Avnet/project_PL_PS_new/project_PL_PS_new.srcs/sources_1/bd/design_ps_pl/ip/design_ps_pl_axi_smc_0/bd_0/ip/ip_5/bd_de28_s00a2s_0_ooc.xdc

# XDC: c:/Avnet/project_PL_PS_new/project_PL_PS_new.srcs/sources_1/bd/design_ps_pl/ip/design_ps_pl_axi_smc_0/bd_0/ip/ip_6/bd_de28_sarn_0_ooc.xdc

# XDC: c:/Avnet/project_PL_PS_new/project_PL_PS_new.srcs/sources_1/bd/design_ps_pl/ip/design_ps_pl_axi_smc_0/bd_0/ip/ip_7/bd_de28_srn_0_ooc.xdc

# XDC: c:/Avnet/project_PL_PS_new/project_PL_PS_new.srcs/sources_1/bd/design_ps_pl/ip/design_ps_pl_axi_smc_0/bd_0/ip/ip_8/bd_de28_sawn_0_ooc.xdc

# XDC: c:/Avnet/project_PL_PS_new/project_PL_PS_new.srcs/sources_1/bd/design_ps_pl/ip/design_ps_pl_axi_smc_0/bd_0/ip/ip_9/bd_de28_swn_0_ooc.xdc

# XDC: c:/Avnet/project_PL_PS_new/project_PL_PS_new.srcs/sources_1/bd/design_ps_pl/ip/design_ps_pl_axi_smc_0/bd_0/ip/ip_10/bd_de28_sbn_0_ooc.xdc

# XDC: c:/Avnet/project_PL_PS_new/project_PL_PS_new.srcs/sources_1/bd/design_ps_pl/ip/design_ps_pl_axi_smc_0/bd_0/ip/ip_11/bd_de28_m00s2a_0_ooc.xdc

# XDC: c:/Avnet/project_PL_PS_new/project_PL_PS_new.srcs/sources_1/bd/design_ps_pl/ip/design_ps_pl_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_ps_pl_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Avnet/project_PL_PS_new/project_PL_PS_new.srcs/sources_1/bd/design_ps_pl/ip/design_ps_pl_axi_smc_0/design_ps_pl_axi_smc_0.xci
# IP: The module: 'design_ps_pl_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Avnet/project_PL_PS_new/project_PL_PS_new.srcs/sources_1/bd/design_ps_pl/ip/design_ps_pl_axi_smc_0/bd_0/bd_de28.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Avnet/project_PL_PS_new/project_PL_PS_new.srcs/sources_1/bd/design_ps_pl/ip/design_ps_pl_axi_smc_0/bd_0/ip/ip_0/bd_de28_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Avnet/project_PL_PS_new/project_PL_PS_new.srcs/sources_1/bd/design_ps_pl/ip/design_ps_pl_axi_smc_0/bd_0/ip/ip_1/bd_de28_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Avnet/project_PL_PS_new/project_PL_PS_new.srcs/sources_1/bd/design_ps_pl/ip/design_ps_pl_axi_smc_0/bd_0/ip/ip_2/bd_de28_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Avnet/project_PL_PS_new/project_PL_PS_new.srcs/sources_1/bd/design_ps_pl/ip/design_ps_pl_axi_smc_0/bd_0/ip/ip_3/bd_de28_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Avnet/project_PL_PS_new/project_PL_PS_new.srcs/sources_1/bd/design_ps_pl/ip/design_ps_pl_axi_smc_0/bd_0/ip/ip_4/bd_de28_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Avnet/project_PL_PS_new/project_PL_PS_new.srcs/sources_1/bd/design_ps_pl/ip/design_ps_pl_axi_smc_0/bd_0/ip/ip_5/bd_de28_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Avnet/project_PL_PS_new/project_PL_PS_new.srcs/sources_1/bd/design_ps_pl/ip/design_ps_pl_axi_smc_0/bd_0/ip/ip_6/bd_de28_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Avnet/project_PL_PS_new/project_PL_PS_new.srcs/sources_1/bd/design_ps_pl/ip/design_ps_pl_axi_smc_0/bd_0/ip/ip_7/bd_de28_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Avnet/project_PL_PS_new/project_PL_PS_new.srcs/sources_1/bd/design_ps_pl/ip/design_ps_pl_axi_smc_0/bd_0/ip/ip_8/bd_de28_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Avnet/project_PL_PS_new/project_PL_PS_new.srcs/sources_1/bd/design_ps_pl/ip/design_ps_pl_axi_smc_0/bd_0/ip/ip_9/bd_de28_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Avnet/project_PL_PS_new/project_PL_PS_new.srcs/sources_1/bd/design_ps_pl/ip/design_ps_pl_axi_smc_0/bd_0/ip/ip_10/bd_de28_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Avnet/project_PL_PS_new/project_PL_PS_new.srcs/sources_1/bd/design_ps_pl/ip/design_ps_pl_axi_smc_0/bd_0/ip/ip_11/bd_de28_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Avnet/project_PL_PS_new/project_PL_PS_new.srcs/sources_1/bd/design_ps_pl/ip/design_ps_pl_axi_smc_0/bd_0/ip/ip_12/bd_de28_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Avnet/project_PL_PS_new/project_PL_PS_new.srcs/sources_1/bd/design_ps_pl/ip/design_ps_pl_axi_smc_0/bd_0/ip/ip_1/bd_de28_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Avnet/project_PL_PS_new/project_PL_PS_new.srcs/sources_1/bd/design_ps_pl/ip/design_ps_pl_axi_smc_0/bd_0/ip/ip_1/bd_de28_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Avnet/project_PL_PS_new/project_PL_PS_new.srcs/sources_1/bd/design_ps_pl/ip/design_ps_pl_axi_smc_0/bd_0/ip/ip_5/bd_de28_s00a2s_0_ooc.xdc

# XDC: c:/Avnet/project_PL_PS_new/project_PL_PS_new.srcs/sources_1/bd/design_ps_pl/ip/design_ps_pl_axi_smc_0/bd_0/ip/ip_6/bd_de28_sarn_0_ooc.xdc

# XDC: c:/Avnet/project_PL_PS_new/project_PL_PS_new.srcs/sources_1/bd/design_ps_pl/ip/design_ps_pl_axi_smc_0/bd_0/ip/ip_7/bd_de28_srn_0_ooc.xdc

# XDC: c:/Avnet/project_PL_PS_new/project_PL_PS_new.srcs/sources_1/bd/design_ps_pl/ip/design_ps_pl_axi_smc_0/bd_0/ip/ip_8/bd_de28_sawn_0_ooc.xdc

# XDC: c:/Avnet/project_PL_PS_new/project_PL_PS_new.srcs/sources_1/bd/design_ps_pl/ip/design_ps_pl_axi_smc_0/bd_0/ip/ip_9/bd_de28_swn_0_ooc.xdc

# XDC: c:/Avnet/project_PL_PS_new/project_PL_PS_new.srcs/sources_1/bd/design_ps_pl/ip/design_ps_pl_axi_smc_0/bd_0/ip/ip_10/bd_de28_sbn_0_ooc.xdc

# XDC: c:/Avnet/project_PL_PS_new/project_PL_PS_new.srcs/sources_1/bd/design_ps_pl/ip/design_ps_pl_axi_smc_0/bd_0/ip/ip_11/bd_de28_m00s2a_0_ooc.xdc

# XDC: c:/Avnet/project_PL_PS_new/project_PL_PS_new.srcs/sources_1/bd/design_ps_pl/ip/design_ps_pl_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_ps_pl_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
