# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/rasmus/Documents/RobTek/RE/lab_ps_pl_test/lab_ps_pl_test.srcs/sources_1/bd/design_bram/ip/design_bram_processing_system7_0_0/design_bram_processing_system7_0_0.xci
# IP: The module: 'design_bram_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/rasmus/Documents/RobTek/RE/lab_ps_pl_test/lab_ps_pl_test.srcs/sources_1/bd/design_bram/ip/design_bram_processing_system7_0_0/design_bram_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_bram_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/rasmus/Documents/RobTek/RE/lab_ps_pl_test/lab_ps_pl_test.srcs/sources_1/bd/design_bram/ip/design_bram_processing_system7_0_0/design_bram_processing_system7_0_0.xci
# IP: The module: 'design_bram_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/rasmus/Documents/RobTek/RE/lab_ps_pl_test/lab_ps_pl_test.srcs/sources_1/bd/design_bram/ip/design_bram_processing_system7_0_0/design_bram_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_bram_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
