# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 2
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/rasmus/Documents/RobTek/RE/lab_ps_pl_test/lab_ps_pl_test.cache/wt [current_project]
set_property parent.project_path /home/rasmus/Documents/RobTek/RE/lab_ps_pl_test/lab_ps_pl_test.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part tul.com.tw:pynq-z2:part0:1.0 [current_project]
set_property ip_output_repo /home/rasmus/Documents/RobTek/RE/lab_ps_pl_test/lab_ps_pl_test.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  /home/rasmus/Documents/RobTek/RE/lab_ps_pl_test/lab_ps_pl_test.srcs/sources_1/bd/design_bram/hdl/design_bram_wrapper.vhd
  /home/rasmus/Documents/RobTek/RE/lab_ps_pl_test/lab_ps_pl_test.srcs/sources_1/new/bram_reader.vhd
}
add_files /home/rasmus/Documents/RobTek/RE/lab_ps_pl_test/lab_ps_pl_test.srcs/sources_1/bd/design_bram/design_bram.bd
set_property used_in_implementation false [get_files -all /home/rasmus/Documents/RobTek/RE/lab_ps_pl_test/lab_ps_pl_test.srcs/sources_1/bd/design_bram/ip/design_bram_processing_system7_0_0/design_bram_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/rasmus/Documents/RobTek/RE/lab_ps_pl_test/lab_ps_pl_test.srcs/sources_1/bd/design_bram/ip/design_bram_blk_mem_gen_0_0/design_bram_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rasmus/Documents/RobTek/RE/lab_ps_pl_test/lab_ps_pl_test.srcs/sources_1/bd/design_bram/ip/design_bram_axi_bram_ctrl_0_0/design_bram_axi_bram_ctrl_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rasmus/Documents/RobTek/RE/lab_ps_pl_test/lab_ps_pl_test.srcs/sources_1/bd/design_bram/ip/design_bram_axi_smc_0/bd_0/ip/ip_1/bd_e045_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/rasmus/Documents/RobTek/RE/lab_ps_pl_test/lab_ps_pl_test.srcs/sources_1/bd/design_bram/ip/design_bram_axi_smc_0/bd_0/ip/ip_1/bd_e045_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all /home/rasmus/Documents/RobTek/RE/lab_ps_pl_test/lab_ps_pl_test.srcs/sources_1/bd/design_bram/ip/design_bram_axi_smc_0/bd_0/ip/ip_5/bd_e045_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rasmus/Documents/RobTek/RE/lab_ps_pl_test/lab_ps_pl_test.srcs/sources_1/bd/design_bram/ip/design_bram_axi_smc_0/bd_0/ip/ip_6/bd_e045_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rasmus/Documents/RobTek/RE/lab_ps_pl_test/lab_ps_pl_test.srcs/sources_1/bd/design_bram/ip/design_bram_axi_smc_0/bd_0/ip/ip_7/bd_e045_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rasmus/Documents/RobTek/RE/lab_ps_pl_test/lab_ps_pl_test.srcs/sources_1/bd/design_bram/ip/design_bram_axi_smc_0/bd_0/ip/ip_8/bd_e045_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rasmus/Documents/RobTek/RE/lab_ps_pl_test/lab_ps_pl_test.srcs/sources_1/bd/design_bram/ip/design_bram_axi_smc_0/bd_0/ip/ip_9/bd_e045_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rasmus/Documents/RobTek/RE/lab_ps_pl_test/lab_ps_pl_test.srcs/sources_1/bd/design_bram/ip/design_bram_axi_smc_0/bd_0/ip/ip_10/bd_e045_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rasmus/Documents/RobTek/RE/lab_ps_pl_test/lab_ps_pl_test.srcs/sources_1/bd/design_bram/ip/design_bram_axi_smc_0/bd_0/ip/ip_11/bd_e045_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rasmus/Documents/RobTek/RE/lab_ps_pl_test/lab_ps_pl_test.srcs/sources_1/bd/design_bram/ip/design_bram_axi_smc_0/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rasmus/Documents/RobTek/RE/lab_ps_pl_test/lab_ps_pl_test.srcs/sources_1/bd/design_bram/ip/design_bram_rst_ps7_0_50M_0/design_bram_rst_ps7_0_50M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/rasmus/Documents/RobTek/RE/lab_ps_pl_test/lab_ps_pl_test.srcs/sources_1/bd/design_bram/ip/design_bram_rst_ps7_0_50M_0/design_bram_rst_ps7_0_50M_0.xdc]
set_property used_in_implementation false [get_files -all /home/rasmus/Documents/RobTek/RE/lab_ps_pl_test/lab_ps_pl_test.srcs/sources_1/bd/design_bram/ip/design_bram_rst_ps7_0_50M_0/design_bram_rst_ps7_0_50M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rasmus/Documents/RobTek/RE/lab_ps_pl_test/lab_ps_pl_test.srcs/sources_1/bd/design_bram/ip/design_bram_axi_bram_ctrl_0_bram_0/design_bram_axi_bram_ctrl_0_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rasmus/Documents/RobTek/RE/lab_ps_pl_test/lab_ps_pl_test.srcs/sources_1/bd/design_bram/design_bram_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/rasmus/Documents/RobTek/RE/lab_ps_pl_test/lab_ps_pl_test.srcs/constrs_1/imports/lab_ps_pl_test_help/pynq_constrain.xdc
set_property used_in_implementation false [get_files /home/rasmus/Documents/RobTek/RE/lab_ps_pl_test/lab_ps_pl_test.srcs/constrs_1/imports/lab_ps_pl_test_help/pynq_constrain.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top bram_reader -part xc7z020clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef bram_reader.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file bram_reader_utilization_synth.rpt -pb bram_reader_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
