# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/lab_ps_pl_test_help/pynq_constrain.xdc

# Block Designs: bd/design_bram/design_bram.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_bram || ORIG_REF_NAME==design_bram} -quiet] -quiet

# IP: bd/design_bram/ip/design_bram_processing_system7_0_0/design_bram_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_bram_processing_system7_0_0 || ORIG_REF_NAME==design_bram_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_bram/ip/design_bram_blk_mem_gen_0_0/design_bram_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_bram_blk_mem_gen_0_0 || ORIG_REF_NAME==design_bram_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/design_bram/ip/design_bram_axi_bram_ctrl_0_0/design_bram_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_bram_axi_bram_ctrl_0_0 || ORIG_REF_NAME==design_bram_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/design_bram/ip/design_bram_axi_smc_0/design_bram_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_bram_axi_smc_0 || ORIG_REF_NAME==design_bram_axi_smc_0} -quiet] -quiet

# IP: bd/design_bram/ip/design_bram_rst_ps7_0_50M_0/design_bram_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_bram_rst_ps7_0_50M_0 || ORIG_REF_NAME==design_bram_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/design_bram/ip/design_bram_axi_bram_ctrl_0_bram_0/design_bram_axi_bram_ctrl_0_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_bram_axi_bram_ctrl_0_bram_0 || ORIG_REF_NAME==design_bram_axi_bram_ctrl_0_bram_0} -quiet] -quiet

# XDC: bd/design_bram/design_bram_ooc.xdc
