# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/rasmus/Documents/RobTek/RE/lab_adc_test/lab_adc_test.srcs/sources_1/bd/adc_design/ip/adc_design_auto_pc_0/adc_design_auto_pc_0.xci
# IP: The module: 'adc_design_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/rasmus/Documents/RobTek/RE/lab_adc_test/lab_adc_test.srcs/sources_1/bd/adc_design/ip/adc_design_auto_pc_0/adc_design_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'adc_design_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/rasmus/Documents/RobTek/RE/lab_adc_test/lab_adc_test.srcs/sources_1/bd/adc_design/ip/adc_design_auto_pc_0/adc_design_auto_pc_0.xci
# IP: The module: 'adc_design_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/rasmus/Documents/RobTek/RE/lab_adc_test/lab_adc_test.srcs/sources_1/bd/adc_design/ip/adc_design_auto_pc_0/adc_design_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'adc_design_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
