# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/const.xdc

# Block Designs: bd/design_ps_pl/design_ps_pl.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_ps_pl || ORIG_REF_NAME==design_ps_pl} -quiet] -quiet

# IP: bd/design_ps_pl/ip/design_ps_pl_axi_bram_ctrl_0_0/design_ps_pl_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_ps_pl_axi_bram_ctrl_0_0 || ORIG_REF_NAME==design_ps_pl_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/design_ps_pl/ip/design_ps_pl_axi_smc_0/design_ps_pl_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_ps_pl_axi_smc_0 || ORIG_REF_NAME==design_ps_pl_axi_smc_0} -quiet] -quiet

# IP: bd/design_ps_pl/ip/design_ps_pl_processing_system7_0_0/design_ps_pl_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_ps_pl_processing_system7_0_0 || ORIG_REF_NAME==design_ps_pl_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_ps_pl/ip/design_ps_pl_blk_mem_gen_0_0/design_ps_pl_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_ps_pl_blk_mem_gen_0_0 || ORIG_REF_NAME==design_ps_pl_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/design_ps_pl/ip/design_ps_pl_rst_ps7_0_100M_0/design_ps_pl_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_ps_pl_rst_ps7_0_100M_0 || ORIG_REF_NAME==design_ps_pl_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/design_ps_pl/ip/design_ps_pl_PL_0_0/design_ps_pl_PL_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_ps_pl_PL_0_0 || ORIG_REF_NAME==design_ps_pl_PL_0_0} -quiet] -quiet

# IP: bd/design_ps_pl/ip/design_ps_pl_xadc_wiz_0_0/design_ps_pl_xadc_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_ps_pl_xadc_wiz_0_0 || ORIG_REF_NAME==design_ps_pl_xadc_wiz_0_0} -quiet] -quiet

# IP: bd/design_ps_pl/ip/design_ps_pl_PID_0_0/design_ps_pl_PID_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_ps_pl_PID_0_0 || ORIG_REF_NAME==design_ps_pl_PID_0_0} -quiet] -quiet

# IP: bd/design_ps_pl/ip/design_ps_pl_xlconstant_0_0/design_ps_pl_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_ps_pl_xlconstant_0_0 || ORIG_REF_NAME==design_ps_pl_xlconstant_0_0} -quiet] -quiet

# IP: bd/design_ps_pl/ip/design_ps_pl_xlconstant_1_0/design_ps_pl_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_ps_pl_xlconstant_1_0 || ORIG_REF_NAME==design_ps_pl_xlconstant_1_0} -quiet] -quiet

# IP: bd/design_ps_pl/ip/design_ps_pl_counter_12_0_1/design_ps_pl_counter_12_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_ps_pl_counter_12_0_1 || ORIG_REF_NAME==design_ps_pl_counter_12_0_1} -quiet] -quiet

# IP: bd/design_ps_pl/ip/design_ps_pl_inverter_0_2/design_ps_pl_inverter_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_ps_pl_inverter_0_2 || ORIG_REF_NAME==design_ps_pl_inverter_0_2} -quiet] -quiet

# IP: bd/design_ps_pl/ip/design_ps_pl_comparator_12_0_1/design_ps_pl_comparator_12_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_ps_pl_comparator_12_0_1 || ORIG_REF_NAME==design_ps_pl_comparator_12_0_1} -quiet] -quiet

# IP: bd/design_ps_pl/ip/design_ps_pl_read_clk_0_0/design_ps_pl_read_clk_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_ps_pl_read_clk_0_0 || ORIG_REF_NAME==design_ps_pl_read_clk_0_0} -quiet] -quiet

# XDC: bd/design_ps_pl/design_ps_pl_ooc.xdc
