# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/rasmus/Documents/RobTek/RE/lab_ps_pl_test/lab_ps_pl_test.srcs/sources_1/bd/design_bram/ip/design_bram_axi_smc_0/design_bram_axi_smc_0.xci
# IP: The module: 'design_bram_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/rasmus/Documents/RobTek/RE/lab_ps_pl_test/lab_ps_pl_test.srcs/sources_1/bd/design_bram/ip/design_bram_axi_smc_0/bd_0/bd_e045.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/rasmus/Documents/RobTek/RE/lab_ps_pl_test/lab_ps_pl_test.srcs/sources_1/bd/design_bram/ip/design_bram_axi_smc_0/bd_0/ip/ip_0/bd_e045_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/rasmus/Documents/RobTek/RE/lab_ps_pl_test/lab_ps_pl_test.srcs/sources_1/bd/design_bram/ip/design_bram_axi_smc_0/bd_0/ip/ip_1/bd_e045_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/rasmus/Documents/RobTek/RE/lab_ps_pl_test/lab_ps_pl_test.srcs/sources_1/bd/design_bram/ip/design_bram_axi_smc_0/bd_0/ip/ip_2/bd_e045_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/rasmus/Documents/RobTek/RE/lab_ps_pl_test/lab_ps_pl_test.srcs/sources_1/bd/design_bram/ip/design_bram_axi_smc_0/bd_0/ip/ip_3/bd_e045_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/rasmus/Documents/RobTek/RE/lab_ps_pl_test/lab_ps_pl_test.srcs/sources_1/bd/design_bram/ip/design_bram_axi_smc_0/bd_0/ip/ip_4/bd_e045_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/rasmus/Documents/RobTek/RE/lab_ps_pl_test/lab_ps_pl_test.srcs/sources_1/bd/design_bram/ip/design_bram_axi_smc_0/bd_0/ip/ip_5/bd_e045_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/rasmus/Documents/RobTek/RE/lab_ps_pl_test/lab_ps_pl_test.srcs/sources_1/bd/design_bram/ip/design_bram_axi_smc_0/bd_0/ip/ip_6/bd_e045_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/rasmus/Documents/RobTek/RE/lab_ps_pl_test/lab_ps_pl_test.srcs/sources_1/bd/design_bram/ip/design_bram_axi_smc_0/bd_0/ip/ip_7/bd_e045_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/rasmus/Documents/RobTek/RE/lab_ps_pl_test/lab_ps_pl_test.srcs/sources_1/bd/design_bram/ip/design_bram_axi_smc_0/bd_0/ip/ip_8/bd_e045_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/rasmus/Documents/RobTek/RE/lab_ps_pl_test/lab_ps_pl_test.srcs/sources_1/bd/design_bram/ip/design_bram_axi_smc_0/bd_0/ip/ip_9/bd_e045_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/rasmus/Documents/RobTek/RE/lab_ps_pl_test/lab_ps_pl_test.srcs/sources_1/bd/design_bram/ip/design_bram_axi_smc_0/bd_0/ip/ip_10/bd_e045_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/rasmus/Documents/RobTek/RE/lab_ps_pl_test/lab_ps_pl_test.srcs/sources_1/bd/design_bram/ip/design_bram_axi_smc_0/bd_0/ip/ip_11/bd_e045_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/rasmus/Documents/RobTek/RE/lab_ps_pl_test/lab_ps_pl_test.srcs/sources_1/bd/design_bram/ip/design_bram_axi_smc_0/bd_0/ip/ip_12/bd_e045_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/rasmus/Documents/RobTek/RE/lab_ps_pl_test/lab_ps_pl_test.srcs/sources_1/bd/design_bram/ip/design_bram_axi_smc_0/bd_0/ip/ip_1/bd_e045_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/rasmus/Documents/RobTek/RE/lab_ps_pl_test/lab_ps_pl_test.srcs/sources_1/bd/design_bram/ip/design_bram_axi_smc_0/bd_0/ip/ip_1/bd_e045_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/rasmus/Documents/RobTek/RE/lab_ps_pl_test/lab_ps_pl_test.srcs/sources_1/bd/design_bram/ip/design_bram_axi_smc_0/bd_0/ip/ip_5/bd_e045_s00a2s_0_ooc.xdc

# XDC: /home/rasmus/Documents/RobTek/RE/lab_ps_pl_test/lab_ps_pl_test.srcs/sources_1/bd/design_bram/ip/design_bram_axi_smc_0/bd_0/ip/ip_6/bd_e045_sarn_0_ooc.xdc

# XDC: /home/rasmus/Documents/RobTek/RE/lab_ps_pl_test/lab_ps_pl_test.srcs/sources_1/bd/design_bram/ip/design_bram_axi_smc_0/bd_0/ip/ip_7/bd_e045_srn_0_ooc.xdc

# XDC: /home/rasmus/Documents/RobTek/RE/lab_ps_pl_test/lab_ps_pl_test.srcs/sources_1/bd/design_bram/ip/design_bram_axi_smc_0/bd_0/ip/ip_8/bd_e045_sawn_0_ooc.xdc

# XDC: /home/rasmus/Documents/RobTek/RE/lab_ps_pl_test/lab_ps_pl_test.srcs/sources_1/bd/design_bram/ip/design_bram_axi_smc_0/bd_0/ip/ip_9/bd_e045_swn_0_ooc.xdc

# XDC: /home/rasmus/Documents/RobTek/RE/lab_ps_pl_test/lab_ps_pl_test.srcs/sources_1/bd/design_bram/ip/design_bram_axi_smc_0/bd_0/ip/ip_10/bd_e045_sbn_0_ooc.xdc

# XDC: /home/rasmus/Documents/RobTek/RE/lab_ps_pl_test/lab_ps_pl_test.srcs/sources_1/bd/design_bram/ip/design_bram_axi_smc_0/bd_0/ip/ip_11/bd_e045_m00s2a_0_ooc.xdc

# XDC: /home/rasmus/Documents/RobTek/RE/lab_ps_pl_test/lab_ps_pl_test.srcs/sources_1/bd/design_bram/ip/design_bram_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_bram_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/rasmus/Documents/RobTek/RE/lab_ps_pl_test/lab_ps_pl_test.srcs/sources_1/bd/design_bram/ip/design_bram_axi_smc_0/design_bram_axi_smc_0.xci
# IP: The module: 'design_bram_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/rasmus/Documents/RobTek/RE/lab_ps_pl_test/lab_ps_pl_test.srcs/sources_1/bd/design_bram/ip/design_bram_axi_smc_0/bd_0/bd_e045.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/rasmus/Documents/RobTek/RE/lab_ps_pl_test/lab_ps_pl_test.srcs/sources_1/bd/design_bram/ip/design_bram_axi_smc_0/bd_0/ip/ip_0/bd_e045_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/rasmus/Documents/RobTek/RE/lab_ps_pl_test/lab_ps_pl_test.srcs/sources_1/bd/design_bram/ip/design_bram_axi_smc_0/bd_0/ip/ip_1/bd_e045_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/rasmus/Documents/RobTek/RE/lab_ps_pl_test/lab_ps_pl_test.srcs/sources_1/bd/design_bram/ip/design_bram_axi_smc_0/bd_0/ip/ip_2/bd_e045_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/rasmus/Documents/RobTek/RE/lab_ps_pl_test/lab_ps_pl_test.srcs/sources_1/bd/design_bram/ip/design_bram_axi_smc_0/bd_0/ip/ip_3/bd_e045_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/rasmus/Documents/RobTek/RE/lab_ps_pl_test/lab_ps_pl_test.srcs/sources_1/bd/design_bram/ip/design_bram_axi_smc_0/bd_0/ip/ip_4/bd_e045_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/rasmus/Documents/RobTek/RE/lab_ps_pl_test/lab_ps_pl_test.srcs/sources_1/bd/design_bram/ip/design_bram_axi_smc_0/bd_0/ip/ip_5/bd_e045_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/rasmus/Documents/RobTek/RE/lab_ps_pl_test/lab_ps_pl_test.srcs/sources_1/bd/design_bram/ip/design_bram_axi_smc_0/bd_0/ip/ip_6/bd_e045_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/rasmus/Documents/RobTek/RE/lab_ps_pl_test/lab_ps_pl_test.srcs/sources_1/bd/design_bram/ip/design_bram_axi_smc_0/bd_0/ip/ip_7/bd_e045_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/rasmus/Documents/RobTek/RE/lab_ps_pl_test/lab_ps_pl_test.srcs/sources_1/bd/design_bram/ip/design_bram_axi_smc_0/bd_0/ip/ip_8/bd_e045_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/rasmus/Documents/RobTek/RE/lab_ps_pl_test/lab_ps_pl_test.srcs/sources_1/bd/design_bram/ip/design_bram_axi_smc_0/bd_0/ip/ip_9/bd_e045_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/rasmus/Documents/RobTek/RE/lab_ps_pl_test/lab_ps_pl_test.srcs/sources_1/bd/design_bram/ip/design_bram_axi_smc_0/bd_0/ip/ip_10/bd_e045_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/rasmus/Documents/RobTek/RE/lab_ps_pl_test/lab_ps_pl_test.srcs/sources_1/bd/design_bram/ip/design_bram_axi_smc_0/bd_0/ip/ip_11/bd_e045_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/rasmus/Documents/RobTek/RE/lab_ps_pl_test/lab_ps_pl_test.srcs/sources_1/bd/design_bram/ip/design_bram_axi_smc_0/bd_0/ip/ip_12/bd_e045_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/rasmus/Documents/RobTek/RE/lab_ps_pl_test/lab_ps_pl_test.srcs/sources_1/bd/design_bram/ip/design_bram_axi_smc_0/bd_0/ip/ip_1/bd_e045_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/rasmus/Documents/RobTek/RE/lab_ps_pl_test/lab_ps_pl_test.srcs/sources_1/bd/design_bram/ip/design_bram_axi_smc_0/bd_0/ip/ip_1/bd_e045_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/rasmus/Documents/RobTek/RE/lab_ps_pl_test/lab_ps_pl_test.srcs/sources_1/bd/design_bram/ip/design_bram_axi_smc_0/bd_0/ip/ip_5/bd_e045_s00a2s_0_ooc.xdc

# XDC: /home/rasmus/Documents/RobTek/RE/lab_ps_pl_test/lab_ps_pl_test.srcs/sources_1/bd/design_bram/ip/design_bram_axi_smc_0/bd_0/ip/ip_6/bd_e045_sarn_0_ooc.xdc

# XDC: /home/rasmus/Documents/RobTek/RE/lab_ps_pl_test/lab_ps_pl_test.srcs/sources_1/bd/design_bram/ip/design_bram_axi_smc_0/bd_0/ip/ip_7/bd_e045_srn_0_ooc.xdc

# XDC: /home/rasmus/Documents/RobTek/RE/lab_ps_pl_test/lab_ps_pl_test.srcs/sources_1/bd/design_bram/ip/design_bram_axi_smc_0/bd_0/ip/ip_8/bd_e045_sawn_0_ooc.xdc

# XDC: /home/rasmus/Documents/RobTek/RE/lab_ps_pl_test/lab_ps_pl_test.srcs/sources_1/bd/design_bram/ip/design_bram_axi_smc_0/bd_0/ip/ip_9/bd_e045_swn_0_ooc.xdc

# XDC: /home/rasmus/Documents/RobTek/RE/lab_ps_pl_test/lab_ps_pl_test.srcs/sources_1/bd/design_bram/ip/design_bram_axi_smc_0/bd_0/ip/ip_10/bd_e045_sbn_0_ooc.xdc

# XDC: /home/rasmus/Documents/RobTek/RE/lab_ps_pl_test/lab_ps_pl_test.srcs/sources_1/bd/design_bram/ip/design_bram_axi_smc_0/bd_0/ip/ip_11/bd_e045_m00s2a_0_ooc.xdc

# XDC: /home/rasmus/Documents/RobTek/RE/lab_ps_pl_test/lab_ps_pl_test.srcs/sources_1/bd/design_bram/ip/design_bram_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_bram_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
